# Generated by Django 4.1 on 2024-04-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="spending_limit",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
