# Generated by Django 4.1 on 2024-04-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_bankaccount_spending_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersetting",
            name="budget_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_setting",
                to="accounts.bankaccount",
            ),
        ),
    ]
